---
- hosts: all
  roles:
    - mnussbaum.base16-builder-ansible
  tasks:
    - set_fact:
        base16_theme: tomorrow-night
    
    - name: Install pystache to build base16 templates
      pacaur:
        name: python-pystache
        state: present
      become: true

    - name: Generate base16-shell config
      base16_builder:
        scheme: "{{ base16_theme }}"
        template: shell
      register: base16_shell

    - name: Write base16-shell theme to a location sourced by my ZSH profile
      copy:
        content: "{{ base16_shell['schemes'][base16_theme]['shell']['scripts']['base16-' + base16_theme + '.sh'] }}"
        dest: ~/.config/zsh/base16-colors.sh

    - name: Generate base16-i3 config
      base16_builder:
        scheme: "{{ base16_theme }}"
        template: i3
      register: base16_i3

    - name: Render my i3 config using the base16 theme from above
      template:
        src: templates/i3_config.j2
        dest: ~/.config/i3/config

  # vim:ft=ansible:
