---
- hosts: all
  become: true
  handlers:
    - name: Regenerate grub.cfg
      command: grub-mkconfig -o /boot/grub/grub.cfg
  tasks:
    - include: tasks/packaging.yml
    - include: tasks/boot.yml
    - include: tasks/networking.yml
    - include: tasks/power.yml

# Disk
  # Disable journaling
  # Enable swap file
  # Other stuff from https://github.com/alghanmi/ubuntu-desktop_setup/wiki/SSD-Configuration-on-Linux
# Limit journald total and max file sizes - https://github.com/groks/ansible-systemd-journal/blob/master/tasks/main.yml
# Power management
# Time sync
# Remove psmouse errors from dmesg
# Networking
# Audio
# GUI
# Mouse input
# Printing
# PLs
  # Ruby
  # Python
  # Rust
  # Node
  # Java
# Users
  # mnussbaum
  #   dotfiles
  #   editor
  #   shell
# CLI Apps
  # vim
  # jq
  # aws
# GUI Apps
  # music
  # video
  # browsers
  # PDF
  # notepad
  # dropbox
  # Littlesnitch replacemend
# Password sync
