# vim:ft=ansible:
---
- hosts: all
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
      default: "password"
  handlers:
    - name: Regenerate grub.cfg
      command: grub-mkconfig -o /boot/grub/grub.cfg
      become: true
    - name: Regenerate mkinitcpio ramdisk
      command: mkinitcpio -p linux
      become: true
  roles:
    - mnussbaum.base16-builder-ansible
  tasks:
    - name: Set base16 theme
      set_fact:
        base16_theme: unikitty-dark
      tags: [base16]
    - import_tasks: tasks/set-window-manager-facts.yml
      tags: [base16]
    - import_tasks: tasks/time.yml
    - include_tasks: tasks/boot.yml
      tags: [bootstrap]
    - import_tasks: tasks/trim.yml
    - include_tasks: tasks/user.yml
      tags: [bootstrap]
    - include_tasks: tasks/networking-packages.yml
      tags: [bootstrap]
    - import_tasks: tasks/start-networking.yml
    - import_tasks: tasks/network-online.yml
    - import_tasks: tasks/packaging.yml
    - name: Set package manager to pacaur
      set_fact:
        ansible_pkg_mgr: pacaur
    - import_tasks: tasks/cli-tools.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/python.yml
    - import_tasks: tasks/rust.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/golang.yml
    - import_tasks: tasks/global-environment-configuration.yml
    - import_tasks: tasks/gitconfig.yml
    - import_tasks: tasks/termite.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/power.yml
    - import_tasks: tasks/qemu-guest.yml
      when: ansible_virtualization_role == "guest"
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/x11.yml
    - import_tasks: tasks/x11-socket-activation.yml
      when: window_manager == "i3"
    - import_tasks: tasks/libinput.yml
    - import_tasks: tasks/sway.yml
      when: window_manager == "sway"
    - import_tasks: tasks/i3.yml
      when: window_manager == "i3"
    - import_tasks: tasks/gtk.yml
    - import_tasks: tasks/brightness.yml
    - import_tasks: tasks/audio.yml
    - import_tasks: tasks/firefox.yml
    - import_tasks: tasks/deluge-torrents.yml
    - import_tasks: tasks/firejail.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/dropbox.yml

# Bootstrap:
  # Convert script to re-entrant ansible
  # Configure wifi for after reboot
  # Automate partitioning or restoring from a partition dump
  # Install SSH key
# Security harden
# Printing
# PLs
  # Ruby
  # Python
  # Javascript
# Make ansible only prompt for new-user pw when needed
# GUI Apps
  # music
  # video
  # PDF
  # notepad
  # dropbox
  # Littlesnitch replacement
# Password sync
# Get some wallpaper
