---
- hosts: all
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
      default: "password"
  handlers:
    - name: Regenerate grub.cfg
      command: grub-mkconfig -o /boot/grub/grub.cfg
      become: true
    - name: Regenerate mkinitcpio ramdisk
      command: mkinitcpio -p linux
      become: true
  tasks:
    - include: tasks/time.yml
    - include: tasks/packaging.yml
    - include: tasks/boot.yml
      tags: [bootstrap]
    - include: tasks/trim.yml
    - include: tasks/user.yml
      tags: [bootstrap]
    - include: tasks/networking-packages.yml
      tags: [bootstrap]
    - include: tasks/start-networking.yml
    - include: tasks/cli-tools.yml
    - include: tasks/package-update.yml
    - include: tasks/python.yml
    - include: tasks/neovim.yml
    - include: tasks/power.yml
    - include: tasks/vagrant-guest.yml
    - include: tasks/fonts.yml
    - include: tasks/gui.yml
    - include: tasks/brightness.yml
    - include: tasks/audio.yml
    - include: tasks/firefox.yml

# Bootstrap:
  # Convert script to re-entrant ansible
  # Configure wifi for after reboot
  # Automate partitioning or restoring from a partition dump
  # Fix Grub not finding Windows
  # Fix Grub two-password for decryption
  # Install SSH key
# Security harden
# Make external displays easy to add
# Make external speakers easy to add
# Fix errors from systemd units starting too early
# Remove psmouse errors from dmesg
# Printing
# PLs
  # Ruby
  # Python
  # Rust
  # Node
  # Java
# Make ansible only prompt for new-user pw when needed
# Users
  # mnussbaum
  #   dotfiles
  #   editor
  #   shell
  #   git global config
# GUI Apps
  # music
  # video
  # PDF
  # notepad
  # dropbox
  # Littlesnitch replacemend
# Password sync
