---
- hosts: all
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
      default: "password"
  handlers:
    - name: Regenerate grub.cfg
      command: grub-mkconfig -o /boot/grub/grub.cfg
      become: true
    - name: Regenerate mkinitcpio ramdisk
      command: mkinitcpio -p linux
      become: true
  tasks:
    - include: tasks/packaging.yml
    - include: tasks/boot.yml
    - include: tasks/user.yml
    - include: tasks/networking.yml
    - include: tasks/cli-tools.yml
    - include: tasks/power.yml
    - include: tasks/vagrant-guest.yml
    - include: tasks/fonts.yml
    - include: tasks/gui.yml
    - include: tasks/brightness.yml
    - include: tasks/audio.yml
    - include: tasks/firefox.yml

# Power management
# Time sync
# Remove psmouse errors from dmesg
# Audio
# GUI
# Printing
# PLs
  # Ruby
  # Python
  # Rust
  # Node
  # Java
# Users
  # mnussbaum
  #   dotfiles
  #   editor
  #   shell
# GUI Apps
  # music
  # video
  # browsers
  # PDF
  # notepad
  # dropbox
  # Littlesnitch replacemend
# Password sync
