---
- name: boot | Install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - efibootmgr
    - grub
    - intel-ucode
    - os-prober

- name: boot | Run os-prober to find other OS
  command: os-prober
  become: true
  changed_when: false

- name: boot | Get power_image size
  command: cat /sys/power/image_size
  register: power_image_size_bytes
  changed_when: false

- name: boot | Configure swapfile
  become: true
  include_role: name="ansible-swapfile"
  vars:
    swapfile_size: "{{ ((power_image_size_bytes.stdout | int) * 1.25) | int }}"
    swapfile_swappiness: 0
    swapfile_location: /swapfile
    vfs_cache_pressure: 50

- name: boot | Get swapfile offset
  shell: filefrag -v /swapfile | awk '{gsub(/\./,""); if($1=="0:"){print $4}}'
  register: swapfile_offset
  changed_when: false
  become: true

- name: boot | Configure grub
  become: true
  notify:
    - Regenerate grub.cfg
  template:
    src: templates/grub.j2
    dest: /etc/default/grub

- name: boot | Install grub
  when: bootstrap is defined and bootstrap == "true"
  notify:
    - Regenerate grub.cfg
  command: >
    grub-install --target=x86_64-efi
                 --efi-directory=/boot/efi
                 --bootloader-id=arch_grub

- name: boot | Install mkinitcpio.conf
  become: true
  notify:
    - Regenerate mkinitcpio ramdisk
  copy:
    src: files/mkinitcpio.conf
    dest: /etc/mkinitcpio.conf
