---
- name: Brightness | Install pacakges
  become: true
  pacaur:
    name: "{{ item }}"
    state: present
  with_items:
    - calise-git
    - illum-git
    - redshift

- name: Brightness | Install redshift config
  copy:
    src: redshift.conf
    dest: "/home/{{ user.name }}/.config/redshift.conf"
    owner: "{{ user.name }}"

- name: Brightness | Install redshift service config
  copy:
    src: redshift@.service
    dest: "/home/{{ user.name }}/.config/systemd/user/redshift@.service"
    owner: "{{ user.name }}"

- name: Brightness | Enable redshift service
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: redshift@0.service
    user: true
    daemon-reload: true

# TODO: Allow this to differ on every machine
- name: Brightness | Install calise config for screen auto-brightness
  become: true
  copy:
    src: calise.conf
    dest: "/etc/calise.conf"

- name: Brightness | Enable calise service
  become: true
  systemd:
    enabled: true
    name: calised.service
    daemon-reload: true

- name: Brightness | Enable illum service for backlight keys
  become: true
  systemd:
    enabled: true
    name: illum.service
    daemon-reload: true
