# vim:ft=ansible:
# TODO: fix redshift, illum and calise for wayland
---
- name: Brightness | Install pacakges
  become: true
  pacaur:
    name: "{{ item }}"
    state: present
  with_items:
    - calise-git
    - illum-git
    - redshift

- name: Brightness | Install redshift config
  copy:
    src: redshift.conf
    dest: "/home/{{ user.name }}/.config/redshift.conf"
    owner: "{{ user.name }}"

- name: Brightness | Install calise config for screen auto-brightness
  become: true
  copy:
    src: calise.conf
    dest: /etc/calise.conf

- name: Brightness | Install calised.service config
  copy:
    src: calised.service
    dest: /etc/systemd/system/calised.service
  become: true

- name: Brightness | Enable calise service
  become: true
  when: ansible_virtualization_role != "guest"
  systemd:
    enabled: true
    name: calised.service
    daemon-reload: true

- name: Brightness | Enable illum service for backlight keys
  become: true
  when: ansible_virtualization_role != "guest"
  systemd:
    enabled: true
    name: illum.service
    daemon-reload: true
