# vim:ft=ansible:
---
- name: CLI Tools | Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - aws-cli
    - bc
    - curl
    - dstat
    - expac
    - git
    - gnupg
    - htop
    - jq
    - lsof
    - net-tools
    - openssh
    - rsync
    - tig
    - unzip
    - vim
    - yajl
    - zsh
    - ruby
    - ripgrep
  become: true

- name: CLI Tools | Install pacaur-install script
  copy:
    dest: /usr/local/bin/install-pacaur
    src: install-pacaur
    mode: a+x
  become: true

- name: CLI Tools | Check pacaur installed
  shell: command -v pacaur >/dev/null
  register: check_pacaur_installed
  ignore_errors: true
  changed_when: false

- name: CLI Tools | Install pacaur
  command: /usr/local/bin/install-pacaur
  when: check_pacaur_installed | failed

- name: CLI Tools | Install fzf
  pacaur:
    name: fzf
    state: present
  become: true

- name: CLI Tools | Install fzf helper scripts
  copy:
    dest: "/usr/local/bin/{{ item | basename }}"
    src: "{{ item }}"
    mode: a+x
  become: true
  with_fileglob:
    - files/fzf_helpers/*
