---
- name: CLI Tools | Install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - aws-cli
    - bc
    - curl
    - dstat
    - expac
    - git
    - gnupg
    - htop
    - jq
    - lsof
    - neovim
    - net-tools
    - rsync
    - yajl
    - tig
    - tmux
    - zsh

- name: CLI Tools | Add cower author's key
  become: "{{ user.name }} "
  gpg_import:
    key_id: 1EB2638FF56C0C53
- name: CLI Tools | Install cower for pacaur
  makepkg:
    name: cower
    state: present
- name: CLI Tools | Install pacaur
  makepkg:
    name: pacaur
    state: present
