---
- name: CLI Tools | Install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - aws-cli
    - bc
    - curl
    - dstat
    - expac
    - git
    - gnupg
    - htop
    - jq
    - lsof
    - neovim
    - net-tools
    - rsync
    - yajl
    - tig
    - tmux
    - zsh

- name: CLI Tools | Check if cower key present
  command: gpg --list-keys 1EB2638FF56C0C53
  ignore_errors: true
  register: cower_key_installed
- name: CLI Tools | Add cower author's key
  command: gpg --recv-key 1EB2638FF56C0C53
  when: cower_key_installed | failed
- name: CLI Tools | Install cower for pacaur
  makepkg:
    name: cower
    state: present
- name: CLI Tools | Install pacaur
  makepkg:
    name: pacaur
    state: present
