# vim:ft=ansible:
---
- name: CLI Tools | Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - aws-cli
    - bc
    - curl
    - dstat
    - expac
    - git
    - gnupg
    - htop
    - jq
    - lsof
    - net-tools
    - openssh
    - rsync
    - tig
    - unzip
    - vim
    - yajl
    - zsh
    - ruby
    - ripgrep
  become: true

- name: CLI Tools | Add cower author's key
  gpg_import:
    key_id: 1EB2638FF56C0C53
- name: CLI Tools | Install cower for pacaur
  become: true
  makepkg:
    name: cower
    state: present
- name: CLI Tools | Install pacaur
  become: true
  makepkg:
    name: pacaur
    state: present

- name: CLI Tools | Install fzf
  pacaur:
    name: fzf
    state: present
  become: true

- name: CLI Tools | Install fzf helper scripts
  copy:
    dest: "/usr/local/bin/{{ item | basename }}"
    src: "{{ item }}"
    mode: a+x
  become: true
  with_fileglob:
    - files/fzf_helpers/*
