---
- name: CLI Tools | Install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - aws-cli
    - bc
    - curl
    - dstat
    - git
    - gnupg
    - htop
    - jq
    - lsof
    - neovim
    - net-tools
    - rsync
    - tig
    - tmux
    - zsh
