---
- name: Deluge torrents | Install pacakges
  become: true
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - pygtk
    - deluge

- name: Deluge torrents | Create config dir
  file:
    path: "/home/{{ user.name }}/.config/deluge"
    state: directory
    owner: "{{ user.name }}"

- name: Deluge torrents | Install configs
  copy:
    dest: "/home/{{ user.name }}/.config/deluge/{{ item | basename }}"
    src: "{{ item }}"
    owner: "{{ user.name }}"
  with_fileglob:
    - files/deluge/*
