---
- name: Firefox | Install packages
  pacaur:
    name: "{{ item }}"
    state: latest
  with_items:
    - firefox
    - firefox-pentadactyl-signed
    - firefox-ublock-origin
    - freshplayerplugin
    - pepper-flash
    - google-talkplugin
    - xorg-server-xvfb
  become: true

- name: Firefox | Make default profile
  command: xvfb-run firefox -CreateProfile "default /home/{{ user.name }}/.mozilla/firefox/default.profile"
  args:
    creates: "/home/{{ user.name }}/.mozilla/firefox/default.profile"
  become: true
  become_user: "{{ user.name }}"

- name: Firefox | Configure firefox
  copy:
    dest: "/home/{{ user.name }}/.mozilla/firefox/default.profile/user.js"
    src: firefox-user.js
    owner: "{{ user.name }}"

- name: Firefox | Configure flash plugin
  copy:
    remote_src: true
    src: /usr/share/freshplayerplugin/freshwrapper.conf.example
    dest: "/home/{{ user.name }}/.config/freshwrapper.conf"
    force: no
    owner: "{{ user.name }}"

- name: Firefox | Enable hardware acceleration for flash plugin
  lineinfile:
    dest: "/home/{{ user.name }}/.config/freshwrapper.conf"
    regexp: "^enable_hwdec ="
    line: "enable_hwdec = 1"
