# vim:ft=yaml.ansible:
---
- name: golang | Install packages
  package:
    name: "{{ item }}"
    state: present
    use: pacaur
  become: yes
  with_items:
    - go
    - go-langserver-git
    - vim-gocode

- name: golang | Create gopath dirs
  file:
    path: "/home/{{ user.name }}/go/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
  with_items:
    - src
    - bin
