# vim:ft=ansible:
---
- name: golang | Install packages
  pacaur:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - go
    - vim-gocode

- name: golang | Create gopath dirs
  file:
    path: "/home/{{ user.name }}/go/{{ item }}"
    state: directory
    owner: "{{ user.name }}"
  with_items:
    - src
    - bin
