# vim:ft=yaml.ansible:
---
- name: GTK | Create config dir
  file:
    path: "/home/{{ user.name }}/.config/gtk-3.0"
    state: directory
    owner: "{{ user.name }}"

- name: GTK | Install configs
  template:
    src: templates/gtk_3_0_settings.ini.j2
    dest: "/home/{{ user.name }}/.config/gtk-3.0/settings.ini"
    owner: "{{ user.name }}"
