# vim:ft=ansible:
---
- name: GTK | Create config dir
  file:
    path: "/home/{{ user.name }}/.config/gtk-3.0"
    state: directory
    owner: "{{ user.name }}"

- name: GTK | Install configs
  copy:
    dest: "/home/{{ user.name }}/.config/gtk-3.0/{{ item | basename }}"
    src: "{{ item }}"
    owner: "{{ user.name }}"
  with_fileglob:
    - files/gtk-3.0/*
