---
- name: GUI Apps | Install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - firefox
  become: true

- name: GUI Apps | Install pacaur packages
  pacaur:
    name: "{{ item }}"
    state: present
  with_items:
    - firefox-pentadactyl-signed
  become: true
