---
- name: GUI Apps | Install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - firefox
    - xorg-server-xvfb
  become: true

- name: GUI Apps | Install pacaur packages
  pacaur:
    name: "{{ item }}"
    state: present
  with_items:
    - firefox-pentadactyl-signed
  become: true

- name: GUI Apps | Make Firefox default profile
  command: xvfb-run firefox -CreateProfile "default /home/{{ user.name }}/.mozilla/firefox/default.profile"
  become: true
  become_user: "{{ user.name }}"

- name: GUI Apps | Enlarge Firefox text size
  lineinfile:
    dest: "/home/{{ user.name }}/.mozilla/firefox/default.profile/prefs.js"
    regexp: '^user_pref\("layout.css.devPixelsPerPx"'
    line: 'user_pref("layout.css.devPixelsPerPx", "1.2");'
