---
- name: GUI | Install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - i3
    - xterm
    - xorg-server
    - xorg-xinit
    - xorg-server-utils
    - rxvt-unicode

- name: GUI | Configure xinitrc
  copy:
    dest: "/home/{{ user.name }}/.xinitrc"
    content: "exec i3"
    owner: "{{ user.name }}"
