---
- name: GUI | Install packages
  pacaur:
    name: "{{ item }}"
    state: latest
  with_items:
    - dmenu
    - i3-gaps
    - i3status
    - libinput
    - libinput-gestures
    - rxvt-unicode
    - xdotool
    - xf86-input-libinput
    - xorg-server
    - xorg-server-utils
    - xorg-xdpyinfo
    - xorg-xinit
    - xorg-xinput
  become: true

- name: GUI | Install X11 socket activation unit
  copy:
    dest: "/home/{{ user.name }}/.config/systemd/user/x11@.socket"
    src: x11@.socket

- name: GUI | Install X11 target
  copy:
    dest: "/home/{{ user.name }}/.config/systemd/user/x11@.target"
    src: x11@.target

- name: GUI | Install xorg-delay service
  copy:
    dest: "/home/{{ user.name }}/.config/systemd/user/xorg-delay@.service"
    src: xorg-delay@.service

- name: GUI | Install xorg service
  copy:
    dest: "/home/{{ user.name }}/.config/systemd/user/xorg@.service"
    src: xorg@.service

- name: GUI | Install xrdb service
  copy:
    dest: "/home/{{ user.name }}/.config/systemd/user/xrdb@.service"
    src: xrdb@.service

- name: GUI | Install i3 service
  copy:
    dest: "/home/{{ user.name }}/.config/systemd/user/i3@.service"
    src: i3@.service

- name: GUI | Configure xorg to run with root privileges
  copy:
    dest: /etc/X11/Xwrapper.config
    src: Xwrapper.config
  become: true

- name: GUI | Enable X11 socket
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: x11@0.socket
    user: true
    daemon-reload: true

- name: GUI | Enable X11 target
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: x11@0.target
    user: true
    daemon-reload: true

- name: GUI | Enable xorg service
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: xorg@0.service
    user: true
    daemon-reload: true

- name: GUI | Enable xorg-delay service
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: xorg-delay@0.service
    user: true
    daemon-reload: true

- name: GUI | Enable xrdb service
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: xrdb@0.service
    user: true
    daemon-reload: true

- name: GUI | Enable i3 service
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: i3@0.service
    user: true
    daemon-reload: true

# TODO template display ID, size in this
- name: GUI | Configure screen size
  become: true
  copy:
    src: xorg-monitor.conf
    dest: "/etc/X11/xorg.conf.d/90-monitor.conf"

- name: GUI | Configure Xresources
  template:
    src: templates/Xresources.j2
    dest: "/home/{{ user.name }}/.Xresources"
    owner: "{{ user.name }}"

- name: GUI | Install i3 configs
  file:
    path: "/home/{{ user.name }}/.config/i3"
    owner: "{{ user.name }}"
    state: directory

- name: GUI | Install i3 configs
  copy:
    dest: "/home/{{ user.name }}/.config/i3/config"
    src: i3_config
    owner: "{{ user.name }}"

- name: GUI | Install xorg multitouch config
  copy:
    dest: "/etc/X11/xorg.conf.d/99-multitouch.conf"
    src: xorg-multitouch.conf
  become: true

- name: GUI | Install libinput-gestures.conf
  copy:
    dest: "/home/{{ user.name }}/.config/libinput-gestures.conf"
    src: libinput-gestures.conf
    owner: "{{ user.name }}"

- name: GUI | Install libinput-gestures user service
  copy:
    dest: "/home/{{ user.name }}/.config/systemd/user/libinput-gestures@.service"
    src: libinput-gestures@.service
    owner: "{{ user.name }}"

- name: GUI | Enable libinput-gestures service
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: libinput-gestures@0.service
    user: true
    daemon-reload: true
