---
- name: GUI | Install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - dmenu
    - i3
    - libinput
    - rxvt-unicode
    - wmctrl
    - xdotool
    - xf86-input-libinput
    - xorg-server
    - xorg-server-utils
    - xorg-xdpyinfo
    - xorg-xinit
    - xorg-xinput
    - xterm
  become: true

- name: GUI | Install pacakges
  become: true
  pacaur:
    name: libinput-gestures
    state: present

- name: GUI | Configure xorg to run with root privileges
  copy:
    dest: /etc/X11/Xwrapper.config
    src: Xwrapper.config
  become: true

- name: GUI | Install xorg service
  copy:
    dest: "/home/{{ user.name }}/.config/systemd/user/xorg.service"
    src: xorg.service

- name: GUI | Configure xinitrc
  template:
    dest: "/home/{{ user.name }}/.xinitrc"
    src: templates/xinitrc.j2
    owner: "{{ user.name }}"

- name: GUI | Install user profile to start X
  copy:
    dest: "/home/{{ user.name }}/.profile"
    src: profile
    owner: "{{ user.name }}"

- name: GUI | Install user zprofile
  copy:
    dest: "/home/{{ user.name }}/.zprofile"
    src: zprofile
    owner: "{{ user.name }}"

- name: GUI | Install i3 configs
  file:
    path: "/home/{{ user.name }}/.config/i3"
    owner: "{{ user.name }}"
    state: directory

- name: GUI | Install i3 configs
  copy:
    dest: "/home/{{ user.name }}/.config/i3/config"
    src: i3_config
    owner: "{{ user.name }}"

- name: GUI | Install xorg multitouch config
  copy:
    dest: "/etc/X11/xorg.conf.d/99-multitouch.conf"
    src: xorg-multitouch.conf
  become: true

- name: GUI | Install libinput-gestures.conf
  copy:
    dest: "/home/{{ user.name }}/.config/libinput-gestures.conf"
    src: libinput-gestures.conf
    owner: "{{ user.name }}"

- name: GUI | Install libinput-gestures user service
  copy:
    dest: "/home/{{ user.name }}/.config/systemd/user/libinput-gestures.service"
    src: libinput-gestures.service
    owner: "{{ user.name }}"

- name: GUI | Enable libinput-gestures service
  become: true
  become_user: "{{ user.name }}"
  systemd:
    enabled: true
    name: libinput-gestures.service
    user: true
    daemon-reload: true
