---
- name: GUI | Install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - dmenu
    - i3
    - rxvt-unicode
    - xorg-server
    - xorg-server-utils
    - xorg-xdpyinfo
    - xorg-xinit
    - xterm

- name: GUI | Configure xinitrc
  copy:
    dest: "/home/{{ user.name }}/.xinitrc"
    content: "xrandr --dpi 192 && exec i3"
    owner: "{{ user.name }}"

- name: GUI | Start X at boot
  copy:
    dest: "/home/{{ user.name }}/.zprofile"
    src: zprofile
    owner: "{{ user.name }}"

- name: GUI | Install i3 configs
  file:
    path: "/home/{{ user.name }}/.config/i3"
    owner: "{{ user.name }}"
    state: directory

- name: GUI | Install i3 configs
  copy:
    dest: "/home/{{ user.name }}/.config/i3/config"
    src: i3_config
    owner: "{{ user.name }}"
