---
- name: GUI | Install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - dmenu
    - i3
    - xterm
    - xorg-server
    - xorg-xinit
    - xorg-server-utils
    - rxvt-unicode

- name: GUI | Configure xinitrc
  copy:
    dest: "/home/{{ user.name }}/.xinitrc"
    content: "exec i3"
    owner: "{{ user.name }}"

- name: GUI | Start X at boot
  copy:
    dest: "/home/{{ user.name }}/.zprofile"
    src: zprofile
    owner: "{{ user.name }}"

- name: GUI | Install i3 configs
  copy:
    dest: "/home/{{ user.name }}/.config/i3/config"
    src: i3_config
    owner: "{{ user.name }}"
