---
- name: kde-wayland | Install packages
  become: true
  pacman:
    name: mesa-libgl
    state: absent

- name: kde-wayland | Install packages
  pacaur:
    name: "{{ item }}"
    state: present
  with_items:
    - breeze-kde4
    - kde-applications-meta
    - libinput
    - libinput-gestures
    - mesa
    - plasma-meta
    - plasma-wayland-session
    - sddm
    - vulkan-intel
    - xdotool
    - xorg-server
    - xorg-server-utils
    - xorg-xdpyinfo
    - xorg-xinput
  become: true

- name: kde-wayland | Configure xorg to run with root privileges
  copy:
    dest: /etc/X11/Xwrapper.config
    src: Xwrapper.config
  become: true

- name: kde-wayland | Install xorg multitouch config
  copy:
    dest: "/etc/X11/xorg.conf.d/99-multitouch.conf"
    src: xorg-multitouch.conf
  become: true

- name: kde-wayland | Enable SDDM
  become: true
  systemd:
    enabled: true
    name: sddm.service
    daemon-reload: true
