---
- name: multitouch | Install packages
  register: packages_installed
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - libinput
    - wmctrl
    - xf86-input-libinput
    - xorg-xinput
    - xdotool

- name: multitouch | Restart i3
  when: packages_installed.changed
  command: i3-msg restart
  notify: Reload i3

- name: multitouch | Get trackpad device name
  shell: xinput list | grep Touchpad | awk '{ print $3,$4,$5 }'
  register: trackpad

# Ideally these should be templated into a seconday i3 config file

- name: multitouch | Start libinput-gestures
  notify: Reload i3
  lineinfile:
    dest: "/home/{{ user.name }}/.config/i3/config"
    line: "exec --no-startup-id libinput-gestures"

- name: multitouch | Enable multi-finger click
  notify: Reload i3
  lineinfile:
    dest: "/home/{{ user.name }}/.config/i3/config"
    line: 'exec xinput set-prop "{{ trackpad.stdout }}" "libinput Click Method Enabled" 0 1'

- name: multitouch | Enable tap to click
  notify: Reload i3
  lineinfile:
    dest: "/home/{{ user.name }}/.config/i3/config"
    line: 'exec xinput set-prop "{{ trackpad.stdout }}" "libinput Tapping Enabled" 1'


- name: multitouch | Enable natural scrolling
  notify: Reload i3
  lineinfile:
    dest: "/home/{{ user.name }}/.config/i3/config"
    line: 'exec xinput set-prop "{{ trackpad.stdout }}" "libinput Natural Scrolling Enabled" 1'

- name: multitouch | Increase mouse speed
  notify: Reload i3
  lineinfile:
    dest: "/home/{{ user.name }}/.config/i3/config"
    line: 'exec xinput set-prop "{{ trackpad.stdout }}" "libinput Accel Speed" 1'
