---
- set_fact:
    nvim_config_dir: "/home/{{ user.name }}/.config/nvim"
    nvim_data_dir: "/home/{{ user.name }}/.local/share/nvim"
    vim_plugins:
      - "Shougo/deoplete.nvim"
      - "pearofducks/ansible-vim"
      - "shmay/vim-yaml"

- name: nvim | Ensure nvim config and data dirs exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nvim_config_dir }}"
    - "{{ nvim_data_dir }}"
    - "{{ nvim_data_dir }}/plugged"
    - "{{ nvim_data_dir }}/site/autoload"

- name: nvim | Install neovim-git
  pacaur:
    name: neovim-git
    state: present

- name: nvim | Install python-neovim
  pip: name=neovim
  become: true

- name: nvim | Download vim-plug installer
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ nvim_data_dir }}/site/autoload/plug.vim"

- name: nvim | Install init.vim config
  template:
    src: templates/neovim/init.vim.j2
    dest: "{{ nvim_config_dir }}/init.vim"

- name: nvim | Install vim-plug.vim config
  template:
    src: templates/neovim/vim-plug.vim.j2
    dest: "{{ nvim_config_dir }}/vim-plug.vim"
  register: vim_plug_config

- name: nvim | Install vim plugins
  command: nvim --headless -n -c ":PlugInstall" -c ":qa!"
  when: vim_plug_config.changed

- name: nvim | Install vim plugins
  copy:
    src: files/neovim_plugins/
    dest: "{{ nvim_config_dir }}/plugin"
