---
- set_fact:
    dein_install_dir: "/home/{{ user.name }}/.config/nvim/dein"
    nvim_config_dir: "/home/{{ user.name }}/.config/nvim"
    nvim_plugin_dir: "/home/{{ user.name }}/.config/nvim/dein_plugin"
    user_data_dir: "/home/{{ user.name }}/.local/share"

- name: nvim | Ensure nvim config and user data dirs exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nvim_config_dir }}"
    - "{{ nvim_plugin_dir }}"

- name: nvim | Install neovim-git
  pacaur:
    name: neovim-git
    state: present

- name: nvim | Install python-neovim
  pip: name=neovim
  become: true

- name: nvim | Download Dein.vim plugin manager installer
  get_url:
    url: https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
    dest: "{{ user_data_dir }}/dein_installer.sh"
    mode: 0755

- name: nvim | Run dein.vim installer
  command: "{{ user_data_dir }}/dein_installer.sh {{ dein_install_dir }}"
  args:
    creates: "{{ dein_install_dir }}"

- name: nvim | Install init.vim config
  template:
    src: templates/neovim/init.vim.j2
    dest: "{{ nvim_config_dir }}/init.vim"

- name: nvim | Install dein.vim config
  template:
    src: templates/neovim/dein.vim.j2
    dest: "{{ nvim_config_dir }}/dein.vim"
  vars:
    vim_plugins:
      - "Shougo/deoplete.nvim"
  register: dein_config

- name: nvim | Install vim plugins
  command: nvim --headless -n -c ":call dein#install()" -c ":qa!"
  when: dein_config.changed
