# vim:ft=yaml.ansible:
---
- set_fact:
    nvim_config_dir: "/home/{{ user.name }}/.config/nvim"
    nvim_data_dir: "/home/{{ user.name }}/.local/share/nvim"
    vim_plugins:
      - "'Shougo/deoplete.nvim', {'do': ':UpdateRemotePlugins'}"
      - "'fatih/vim-go', {'do': ':GoInstallBinaries'}"
      - "'jlanzarotta/bufexplorer'"
      - "'junegunn/fzf', {'dir': '/home/{{ user.name }}/.fzf', 'do': './install --all'}"
      - "'junegunn/fzf.vim'"
      - "'neomake/neomake'"
      - "'pearofducks/ansible-vim'"
      - "'racer-rust/vim-racer'"
      - "'rust-lang/rust.vim'"
      - "'scrooloose/nerdtree'"
      - "'sebastianmarkow/deoplete-rust'"
      - "'shmay/vim-yaml'"
      - "'tomtom/tcomment_vim'"
      - "'tpope/vim-fugitive'"
      - "'zchee/deoplete-go', {'do': 'make'}"

- name: nvim | Ensure nvim config and data dirs exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
  with_items:
    - "{{ nvim_config_dir }}"
    - "{{ nvim_data_dir }}"
    - "{{ nvim_data_dir }}/plugged"
    - "{{ nvim_data_dir }}/site/autoload"

- name: nvim | Install neovim packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - neovim-git
    - python-neovim

- name: nvim | Download vim-plug installer
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ nvim_data_dir }}/site/autoload/plug.vim"
    owner: "{{ user.name }}"

- name: nvim | Install init.vim config
  copy:
    src: neovim/init.vim
    dest: "{{ nvim_config_dir }}/init.vim"
    owner: "{{ user.name }}"

- name: nvim | Install vim-plug.vim config
  template:
    src: templates/neovim/vim-plug.vim.j2
    dest: "{{ nvim_config_dir }}/vim-plug.vim"
    owner: "{{ user.name }}"
  register: vim_plug_config

- name: nvim | Install nvim plugins
  command: nvim --headless -n -c ":PlugInstall" -c ":qa!"
  when: vim_plug_config.changed

- name: nvim | Install nvim configs
  copy:
    src: files/neovim/plugin/
    dest: "{{ nvim_config_dir }}/plugin"
    owner: "{{ user.name }}"

- name: nvim | Generate base16 configs
  base16_builder:
    scheme: "{{ base16_scheme }}"
    template: vim
    schemes_source: "{{ base16_schemes_source }}"
  register: base16_vim
  tags: [base16]

- name: nvim | Write base16 configs to a file
  copy:
    content: "{{ base16_vim['schemes'][base16_scheme]['vim']['colors']['base16-' + base16_scheme + '.vim'] }}"
    dest: ~/.config/nvim/plugin/base16.vim
    owner: "{{ user.name }}"
  tags: [base16]
