---
- name: power | Install TLP
  package:
    name: tlp
    state: latest
- name: power | Install TLP Radio controls
  package:
    name: tlp-rdw
    state: latest

- name: power | Disable systemd-rfkill
  service:
    name: systemd-rfkill
    enabled: no
    state: stopped
- name: power | Enable TLP
  service:
    name: tlp
    enabled: yes
    state: started
- name: power | Enable TLP Sleep
  service:
    name: tlp-sleep
    enabled: yes

- name: power | Install suspend-sedation service
  copy:
    src: files/suspend-sedation.service
    dest: /etc/systemd/system/suspend-sedation.service
- name: power | Enable suspend-sedation service
  service:
    name: suspend-sedation
    enabled: yes

# Lock screen on suspend https://gist.github.com/raphiz/d69859645a9da08a0cf0778f42932120
# Enable wake on keypress
# Enable wake on mouse
