---
- name: power | Install TLP
  package:
    name: tlp
    state: latest
- name: power | Install TLP Radio controls
  package:
    name: tlp-rdw
    state: latest

- name: power | Disable systemd-rfkill
  service:
    name: systemd-rfkill
    enabled: no
    state: stopped
- name: power | Enable TLP
  service:
    name: tlp
    enabled: yes
    state: started
- name: power | Enable TLP Sleep
  service:
    name: tlp-sleep
    enabled: yes

# Enable suspend on lid close
# Enable wake on lid open
# Enable wake on keypress
# Enable wake on mouse
# Enable suspend-to-hibernate
