# vim:ft=ansible:
---
- name: vagrant-guest | Blacklist coretemp module
  when: ansible_virtualization_role == "guest"
  become: true
  notify:
    - Regenerate mkinitcpio ramdisk
  copy:
    content: "blacklist coretemp"
    dest: "/etc/modprobe.d/blacklist_coretemp.conf"
