# vim:ft=yaml.ansible:
---
- name: Ruby | Install packages
  package:
    name: "{{ item }}"
    state: present
    use: pacaur
  become: true
  with_items:
    - ruby-bundler
    - ruby-rubocop
    - ruby-solargraph

- name: Ruby | Install global gemrc
  become: true
  copy:
    src: files/gemrc
    dest: /etc/gemrc

- name: Ruby | Install rubocop config
  become: true
  copy:
    src: files/rubocop.yml
    dest: "/home/{{ user.name }}/.rubocop.yml"
    owner: "{{ user.name }}"
