# vim:ft=yaml.ansible:
---
- name: Secrets | Install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - pass
    - browserpass
    - firefox-browserpass

- name: Secrets | Install Firefox Firejail profile to grant password-store access
  become: true
  copy:
    src: files/firejail-firefox-common.local
    dest: /etc/firejail/firefox-common.local

- name: Secrets | Initialize password store
  command: "pass init {{ user.name }}"
  args:
    creates: "/home/{{ user.name }}/.password-store"
