# vim:ft=ansible:
---
- name: Window manager facts | i3
  set_fact:
    window_manager: i3
  when: ansible_virtualization_role == "guest"

- name: Window manager facts | sway
  set_fact:
    window_manager: sway
  when: ansible_virtualization_role != "guest"
