# vim:ft=yaml.ansible:
---
- name: sway | Create config dir
  file:
    path: "/home/{{ user.name }}/.config/sway"
    owner: "{{ user.name }}"
    state: directory

- name: sway | Install sway
  package:
    name: sway
    state: present
    use: pacaur
  become: true

- name: sway | Install application launcher script
  copy:
    src: files/launcher
    dest: /usr/local/bin/launcher
    mode: a+x
  become: true

- name: sway | Install sway-mouse-input-ids script
  copy:
    src: files/sway-mouse-input-ids
    dest: /usr/local/bin/sway-mouse-input-ids
    mode: a+x
  become: true

- name: sway | Get mouse input IDs
  command: sway-mouse-input-ids
  register: sway_mouse_input_ids
  changed_when: false
  ignore_errors: true

- name: sway | Generate base16 configs
  base16_builder:
    scheme: "{{ base16_scheme }}"
    template: i3
    schemes_source: "{{ base16_schemes_source }}"
  register: base16_i3
  tags: [base16]

- name: sway | Install config
  template:
    src: templates/sway_and_i3_config.j2
    dest: "/home/{{ user.name }}/.config/sway/config"
  tags: [base16]
