---
- name: user | Create wheel group
  group: name=wheel state=present

- name: user | Configure sudoers
  lineinfile:
    dest: /etc/sudoers.d/ansible
    line: "%wheel ALL=(ALL) ALL"
    state: present
    create: yes
    validate: "visudo -cf %s"

- name: user | Create individual user group
  group: name={{ user.group }} state=present

- name: user | Create user
  user:
    name: "{{ user.name }}"
    groups: "{{ user.group }},wheel"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: "{{ user.shell }}"
    update_password: on_create

- name: user | Create user config dir
  file:
    path: "/home/{{ user.name }}/.config"
    owner: "{{ user.name }}"
    state: directory
