# vim:ft=ansible:
---
- name: user | Create wheel group
  become: true
  group: name=wheel state=present

- name: user | Configure sudoers
  become: true
  lineinfile:
    dest: /etc/sudoers.d/ansible
    line: "%wheel ALL=(ALL) ALL"
    state: present
    create: yes
    validate: "visudo -cf %s"

- name: user | Create individual user group
  become: true
  group: name={{ user.group }} state=present

- name: user | Create user
  become: true
  user:
    name: "{{ user.name }}"
    groups: "{{ user.group }},input,wheel"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: "{{ user.shell }}"
    update_password: on_create

- name: user | Create user config dir
  file:
    path: "/home/{{ user.name }}/.config"
    owner: "{{ user.name }}"
    state: directory

- name: user | Create user source code dir
  file:
    path: "/home/{{ user.name }}/src"
    owner: "{{ user.name }}"
    state: directory

- name: user | Create user systemd dir
  file:
    path: "/home/{{ user.name }}/.config/systemd/user"
    owner: "{{ user.name }}"
    state: directory

- name: user | Install user profile
  template:
    dest: "/home/{{ user.name }}/.profile"
    src: templates/profile.j2
    owner: "{{ user.name }}"

- name: user | Install user zprofile, sourcing profile
  copy:
    dest: "/home/{{ user.name }}/.zprofile"
    src: zprofile
    owner: "{{ user.name }}"
