---
- name: vagrant-guest | Install vagrant kernel modules
  when: ansible_bios_version == "VirtualBox"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - virtualbox-host-dkms
    - virtualbox-guest-dkms
  notify:
    - Regenerate grub.cfg
  become: true
