# vim:ft=ansible:
---
- name: vagrant-guest | Install vagrant kernel modules
  when: ansible_bios_version == "VirtualBox"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - virtualbox-host-dkms
    - virtualbox-guest-dkms
  notify:
    - Regenerate grub.cfg
  become: true

- name: vagrant-guest | Blacklist coretemp module
  when: ansible_bios_version == "VirtualBox"
  become: true
  notify:
    - Regenerate mkinitcpio ramdisk
  copy:
    content: "blacklist coretemp"
    dest: "/etc/modprobe.d/blacklist_coretemp.conf"
