# vim:ft=ansible:
---
- name: ZSH | Install package
  pacaur:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - zsh
    - zsh-syntax-highlighting
    - python-pystache # For base16_builder

- name: ZSH | Install base16 colortest script
  become: true
  file:
    src: /usr/share/zsh/plugins/base16-shell/colortest
    dest: /usr/local/bin/colortest
    state: link

- name: ZSH | Install dircolors config
  copy:
    dest: "/home/{{ user.name }}/.config/dircolors"
    src: dircolors
    owner: "{{ user.name }}"

- name: ZSH | Install zshrc
  copy:
    dest: "/home/{{ user.name }}/.zshrc"
    src: zshrc
    owner: "{{ user.name }}"

- name: ZSH | Create zsh config dir
  file:
    path: "/home/{{ user.name }}/.config/zsh"
    owner: "{{ user.name }}"
    state: directory

- name: ZSH | Generate base16 configs
  base16_builder:
    scheme: "{{ base16_theme }}"
    template: shell
    schemes_source: https://github.com/mnussbaum/base16-schemes-source
  register: base16_shell
  tags: [base16]

- name: ZSH | Install base16 zsh config
  copy:
    dest: "/home/{{ user.name }}/.config/zsh/00-base16.zsh"
    content: "{{ base16_shell['schemes'][base16_theme]['shell']['scripts']['base16-' + base16_theme + '.sh'] }}"
  tags: [base16]

- name: ZSH | Install zsh configs
  copy:
    dest: "/home/{{ user.name }}/.config/zsh/{{ item | basename }}"
    src: "{{ item }}"
    owner: "{{ user.name }}"
  with_fileglob:
    - files/zsh-configs/*
